# Banco de Dados aponta para o nome do serviço Docker em produção
spring.datasource.url=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# JPA sem mostrar SQL em produção
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Selenium remoto URL do container selenium/standalone-chrome
selenium.remote.url=http://selenium:4444/wd/hub

# Scheduler 30 minutos
scheduler.interval.ms=1800000